// Global Config
export const SET_GITHUB_TOKEN = 'SET_GITHUB_TOKEN';

// Repository Config
export const ADD_REPOSITORY_CONFIG = 'ADD_REPOSITORY_CONFIG';
export const DELETE_REPOSITORY_CONFIG = 'DELETE_REPOSITORY_CONFIG';
export const EDIT_REPOSITORY_CONFIG = 'EDIT_REPOSITORY_CONFIG';
export const SET_REPOSITORY_CONFIG = 'SET_REPOSITORY_CONFIG';
